FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  curl \
  && curl -LsSf https://astral.sh/uv/install.sh | sh \
  && apt-get purge -y --auto-remove curl \
  && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml uv.lock* api_users-local.json ./
RUN uv sync --no-cache --no-dev

COPY src/ src/
COPY api.py .

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
