from botsrc.commands._add import add  # noqa
from botsrc.commands._suggest import suggest  # noqa
from botsrc.commands._tag import tag  # noqa
from botsrc.commands._group import group  # noqa
from botsrc.commands._list import list_  # noqa
from botsrc.commands._find import find  # noqa
from botsrc.commands._watch import watch  # noqa
from botsrc.commands._pop import pop  # noqa
from botsrc.commands._guest import guest  # noqa
from botsrc.commands._logs import logs  # noqa
from botsrc.commands._books import books  # noqa
