name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create .env file
      run: echo "${{ secrets.DOTENV_FILE }}" > .env
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: pip install uv
    - name: Sync dependencies (including dev group)
      run: uv sync --all-groups
    - name: Test with pytest
      run: uv run pytest
    - name: Run ruff
      run: uv run ruff check --output-format=github .
    - name: Run mypy
      run: uv run mypy .
